### PR TITLE
Update README.md to have the latest version that this generator works…

### PR DESCRIPTION
**Pull request by dropalways**
... with

with the latest versions of capsolver it fails to parse the config because they they changed config.json in the assets folder to config.js and it isnt in json format anymore

### CODE REVIEW

**Comment by loud2pro** [comment]
-1 this guys a brit

**Comment by dropalways** [comment]
Fuck you loud2pro

**Comment by dropalways** [comment]
> -1 this guys a brit

Fuck you loud2pro

**Comment by NazD11** [comment]
yeah fuck you loud2pro

**Comment by UserRank** [comment]
I think this method isn't #Undetected.

**Comment by pixxxxxel** [comment]
ur grandmother died

**Pull request merged**
